Document: mingw-w64-libtiff
Title: Debian mingw-w64-libtiff Manual
Author: <insert document author here>
Abstract: This manual describes what mingw-w64-libtiff is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/mingw-w64-libtiff/mingw-w64-libtiff.sgml.gz

Format: postscript
Files: /usr/share/doc/mingw-w64-libtiff/mingw-w64-libtiff.ps.gz

Format: text
Files: /usr/share/doc/mingw-w64-libtiff/mingw-w64-libtiff.text.gz

Format: HTML
Index: /usr/share/doc/mingw-w64-libtiff/html/index.html
Files: /usr/share/doc/mingw-w64-libtiff/html/*.html
